theme: jekyll-theme-minimal
title: Claudio Siervi Page
logo: https://w7.pngwing.com/pngs/986/608/png-transparent-computer-icons-github-github-white-face-monochrome.png
description: Welcome! That is my personal blog
show_downloads: false
