theme: jekyll-theme-minimal
title: Claudio Siervi Page
logo: https://user-images.githubusercontent.com/16821891/236596311-7187f31d-6d71-4fec-9e13-d2c874cf0007.jpg
description: Welcome! That is my personal blog
show_downloads: false
