theme: jekyll-theme-minimal
title: Claudio Siervi
logo: https://user-images.githubusercontent.com/16821891/236596311-7187f31d-6d71-4fec-9e13-d2c874cf0007.jpg
description: Welcome to my page! ^^
show_downloads: false
markdown: kramdown
google_analytics: G-W1KRFFCZ55
keywords: claudio siervi, backend, python, software engineer
remove_footer: true
